### ISSUE TITLE
SEO - Index items on Google

### ISSUE THREAD

**Issue by gagarine** [swissbib/vufind#570] opened 2018-01-24 15:51 UTC
Swissbib will be massively more popular if all items was indexed on Google. Of course listing should not be indexed, but items should.

For example this item https://www.swissbib.ch/Record/224516590

Can't be found on Google
![screen shot 2018-01-24 at 16 46 54](https://user-images.githubusercontent.com/164074/35341573-3da1b690-0126-11e8-8c6a-91adf563d449.png)

This would be even more powerful if their will be a page for each location having the item. So if I'm looking on Google "Genève Hello Nasty" I will find it.

**Comment by liowalter** [comment] 2018-01-29 08:21
Duplicate of #258

**Closed by liowalter** 2018-01-29 08:21 UTC
